= Golang Teaching OS - gotos (wip)

A framework to teach the concepts of Operating Systems.
Build your very own operating system around emulated hardware.
Arguably, the most important thing that can come out of this project is the system specification.

If an implementation follows the system specification, processes running ON the emulated, virtualized hardware should run flawlessly, albeit with better or worse performance depending on the implementation.

This project is built around emulating a RISC-V CPU and some generic hardware for I/O.
The CPU runs exclusively in User/Application Mode see _The RISC-V Instruction Set Manual: Volume II: Privileged Spec_ <<rv5vol2>> from https://riscv.org/technical/specifications/ .

== Roadmap

=== Emulation

==== riscv32g target

- [ ] RV32I base instructions (37/40)
- [ ] RV32M extension (0/8)
- [ ] RV32A extension (0/11)
- [ ] RV32F extension (0/26)
- [ ] RV32D extension (0/26)
- [ ] Zicsr extension (0/6)
- [ ] Zifencei extension (0/1)

==== Peripherals

- [ ] MMIO

=== OS

- [ ] Syscalls
- [ ] Synchronization primitives
- [ ] C standard library
- [ ] Scheduler framework
- [ ] MMU framework

=== Applications

- [ ] Shell

== Current state

The current version of main.go loads the two example programs `c-program/minimal.text` and `fib/fib.text` into memory.
The `fib.text` program is loaded at address 0 and `core1` is given address 0 as a base and 2MiB as the memory size.
The `minimal.text` program is loaded at a 2MiB offset and `core2` is given a base address equal to this offset and a 2MiB memory size.
Both cores are then started and awaited until halted before both sets of registers are dumped to the terminal.

== Authors and acknowledgment

.Authors
- mumblingdrunkard

== License

This project is licensed under the traditional MIT license.

[bibliography]
== Bibliography

- [[[rv5vol1]]] Andrew Waterman, Krste Asanović, John Hauser.
_RISC-V ISA Specification: Volume 1, Unprivileged ISA v. 20191213_
- [[[rv5vol2]]] Andrew Waterman, Krste Asanović, John Hauser.
_RISC-V ISA Specification: Volume 2, Privileged Spec v. 20211203_
